### PR TITLE
add official project tags and update project data

### PR DESCRIPTION
**Pull request by chefallan**
This is about the [#30](https://github.com/web3phl/directory/discussions/30) discussion with the tags 

cc: @kquirapas @jnebab @warengonzaga

### CODE REVIEW

**Comment by warengonzaga** [comment]
@itsnalla can you PR this on `dev` branch?

**Review by jnebab — CHANGES_REQUESTED** [review]
Can you also please include the change, RosePad to RoseHub, rosepad.io to rosehub.io. Thanks

**Comment by chefallan** [comment]
> @itsnalla can you PR this on `dev` branch?

Oh sorry i didn't notice the branch. I will PR it to the dev branch and will change RosePad to RoseHub.

**Comment by chefallan** [comment]
Closing this

> Can you also please include the change, RosePad to RoseHub, rosepad.io to rosehub.io. Thanks

thanks for the heads up.

**Comment by warengonzaga** [comment]
Thanks @itsnalla! Thank you for your contribution.

**Pull request merged**
