### PR TITLE
Added more projects and added more links object

### PR DESCRIPTION
**Pull request by chefallan**
[Added The Neighbours Metaverse NFT Project](https://github.com/web3phl/directory-api/commit/5ea192519d56fac3bd36a58bbca5077856e52c99)
[Added PandoProject](https://github.com/web3phl/directory-api/commit/39778eefc9eac5b91d1a24c3528f69efa3116c58)
[Added 8chain](https://github.com/web3phl/directory-api/commit/b07aedea88495e49cc61aa58cee35e98d5fa0f84)
[Added Project Elemento](https://github.com/web3phl/directory-api/pull/2/commits/72c50d0a2ff0898ee2d4e3b98a83b4f525b8e5ed)
[Added PUBLC](https://github.com/web3phl/directory-api/pull/2/commits/7d15819211e69ce8d5b164ebd91f0781da781ddd)
[Added The Mega Maxi](https://github.com/web3phl/directory-api/pull/2/commits/7bea625b4dbff7ae05f389c6b887faacd3c2abd5)
[Added more Links Object on README.md](https://github.com/web3phl/directory-api/pull/2/commits/c7e23938b65d147f101c31b901aa505d3bc29e97)
[Added Royal Labs](https://github.com/web3phl/directory-api/pull/2/commits/e846853b91170941abd49c2a472ae1ea9e0fcb87)

### CODE REVIEW

**Comment by warengonzaga** [comment]
Thank you for your contribution @itsnalla, hey @Zabbb and @kquirapas kindly review the PR thanks!

**Comment by kquirapas** [comment]
Will review later when I wake up

**Comment by chefallan** [comment]
> Thank you for your contribution @itsnalla, hey @Zabbb and @kquirapas kindly review the PR thanks!

No problem bro, tuloy ko ata bukas pag d busy.

**Review by kquirapas — APPROVED** [review]

**Review by kquirapas — COMMENTED** [review]
LGTM

**Pull request merged**
