### PR TITLE
☕ CHORE: add new set of projects and update readme

### PR DESCRIPTION
**Pull request by chefallan**
Added Projects:
- [Added Playgroundzero.io](https://github.com/web3phl/directory-api/pull/4/commits/4638b81b26e2d02458e8210008dca9a7ac0e200a)
- [Added Decentralized Automotive Organization](https://github.com/web3phl/directory-api/pull/4/commits/88def5d249d9528f94f63d28cf26312c021b9c3c)
- [Added Tiny Geisha](https://github.com/web3phl/directory-api/pull/4/commits/258903f53d3dcfd597372ca1ac2dac235b1a8e84)
- [added CRYPTOGUPPIES](https://github.com/web3phl/directory-api/pull/4/commits/58278d8f838f0f1b02d4a54b1ba611ecc91f1af5)
- [Added Kryptomon](https://github.com/web3phl/directory-api/pull/4/commits/2a0f5563451546370d04d32738e53e8c3272bde7)
- [Added BlockPinas](https://github.com/web3phl/directory-api/pull/4/commits/6881b0336df14d9c5a9b38c0a97c76ad228ed8b2)
- [Added Chibverse](https://github.com/web3phl/directory-api/pull/4/commits/bf364c266d1c25d9e45f1b874949134d958b1d7d)
- [Added X3](https://github.com/web3phl/directory-api/pull/4/commits/aaa8c094b8b3a09930a10d029ff76e6b9b9cfa37)
- [Added Arkayv](https://github.com/web3phl/directory-api/pull/4/commits/1d1f95b9cf6a52bb8f2cccc51ff9bc5310016221)
- [Added Gryph](https://github.com/web3phl/directory-api/pull/4/commits/6d85d146385a9374f4ea311e4b99e4e183512584)
- [Added Rising Eggplants](https://github.com/web3phl/directory-api/pull/4/commits/b8fc0b62d5a220bcb997a2ae4d91608fe0af14fb)
- [Added Draper Startup House Manila](https://github.com/web3phl/directory-api/pull/4/commits/2a4745a1d909f2e405994f2d0ca815200cb8705e)
- [Added Hammy Ville](https://github.com/web3phl/directory-api/pull/4/commits/32c72aaf811020bcbbcf27d2bc211c27b95031fb)
- [Added Pillow Fund](https://github.com/web3phl/directory-api/pull/4/commits/30aaa885f072f32db1a8aa8673f122bbb198a9df)
- [Added Ikigai Animation Studio](https://github.com/web3phl/directory-api/pull/4/commits/8e571cdc621508135a052ecc0839053a6b1df4ec)
- [Added The Newbs](https://github.com/web3phl/directory-api/pull/4/commits/ee4aaaecfa75750cdc37019cefb8627088bdad4e)
- [Added Delysium](https://github.com/web3phl/directory-api/pull/4/commits/d9d9e7a643329150399d9073607ec3ef45e9c8d3)
- [Added PZOO](https://github.com/web3phl/directory-api/pull/4/commits/327194804c7aa8bf4b2fe25bf29903b579688629)
- [Added Heroes Uprising](https://github.com/web3phl/directory-api/pull/4/commits/756b93bdb9aa17b2e63d4d3afe0d2a9208dcbc24)
- [Added Anuraverse](https://github.com/web3phl/directory-api/pull/4/commits/0d5b5bee2bd755677569ff8444a705e2ae929e58)
- [Added PNGUIN](https://github.com/web3phl/directory-api/pull/4/commits/4afc601080ac142c9968123e22a911f3bce1e53b)
- [Added Greedy Takeshis](https://github.com/web3phl/directory-api/pull/4/commits/0bec5cf7414c4a04400470f688c30fed6d910678)
- [Added NFTHost and changed Greedy Takeshis verification to false](https://github.com/web3phl/directory-api/pull/4/commits/777bdd2ebabf93b93a603f2eaf4cb9bedf8357ac)
- [Added Coin Vault PH](https://github.com/web3phl/directory-api/pull/4/commits/2be79cfac75e97a6ff23a37c96db2af99690e1a9)

Fixed:
- [Fixed some typo on project ID's and added dashes](https://github.com/web3phl/directory-api/pull/4/commits/2dafe3b84f652f3283813944e96e4f3ab3886f70)
- [fixed the issue of the JSON conflict](https://github.com/web3phl/directory-api/pull/4/commits/0767103b30cccb127ea6eb2aa92a9ab08aacd5aa)

Added:
- [added more project format links](https://github.com/web3phl/directory-api/pull/4/commits/d094bc05848df066c13d575692f14ace727f7901)
- [Added linkedin link format](https://github.com/web3phl/directory-api/pull/4/commits/b8421aeefa5e1b2d6c75f009c46fb0a7dd1a7e0e)
- [Added Pitch Deck link section](https://github.com/web3phl/directory-api/pull/4/commits/334893a15c6805690ab1b10167042cd8147ad4fb)

### CODE REVIEW

**Comment by warengonzaga** [comment]
Hey @itsnalla, thank you for completing the list, the issue is that one of your JSON files has a conflict. Can you double-check your JSON entry? Also, I saw cryptoguppies has a double entry in your list.

**Comment by chefallan** [comment]
> Hey @itsnalla, thank you for completing the list, the issue is that one of your JSON files has a conflict. Can you double-check your JSON entry? Also, I saw cryptoguppies has a double entry in your list.

about the cryptoguppies, it's just the description i put. I duplicate it by mistake. And will review the JSON files.

**Comment by warengonzaga** [comment]
Hey @kquirapas can you review this?

**Review by kquirapas — APPROVED** [review]
LGTM

**Pull request merged**
